### PR TITLE
Day 1 Mini Project

### PR DESCRIPTION
**Pull request by Sumitm6879**
Selecting a Character from a dropdown and getting a uniqe response to each selection

### CODE REVIEW

**Comment by ialimustufa** [comment]
Hello @Sumitm6879,

Add Day 1 mini project in /student-projects/day1

Thanks!

**Comment by Sumitm6879** [comment]
added it in the /student-projects/day1

**Comment by ialimustufa** [comment]
Hey @Sumitm6879,

Rename the your folder to this format - yourname-projectname

**Comment by Sumitm6879** [comment]
Name of the folder changed to the given format

**Review by ialimustufa — APPROVED** [review]
Looks Good!

**Pull request merged**
